reactivegroup/capa

sdk-component/pom.xml
sdk-component/src/test/java/group/rxcloud/capa/component/http/CapaHttpBuilderTest.java
sdk/src/test/java/group/rxcloud/capa/rpc/CapaRpcClientBuilderTest.java
sdk/src/test/java/group/rxcloud/capa/rpc/CapaRpcClientHttpTest.java
sdk/src/test/java/group/rxcloud/capa/rpc/TestCapaHttp.java
sdk/src/test/java/group/rxcloud/capa/rpc/domain/InvokeMethodRequestBuilderTest.java
sdk/src/test/resources/capa-component.properties

Add unit test in the module of sdk about rpc
#11 

test: add ut about rpc in sdk

---

sdk-component/src/test/java/group/rxcloud/capa/component/configstore/CapaConfigStoreBuilderTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/configstore/ConfigurationItemTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/configstore/GetRequestTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/configstore/StoreConfigTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/configstore/SubscribeReqTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/configstore/SubscribeRespTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/configstore/TestCapaConfigStore.java
sdk-component/src/test/java/group/rxcloud/capa/component/configstore/TestObjectSerializer.java
sdk-component/src/test/resources/capa-component.properties
sdk-spi/src/test/java/group/rxcloud/capa/spi/configstore/CapaConfigStoreSpiTest.java
sdk-spi/src/test/java/group/rxcloud/capa/spi/configstore/TestCapaConfigStoreSpiImpl.java
sdk/pom.xml
sdk/src/main/java/group/rxcloud/capa/configuration/CapaConfigurationClientStore.java
sdk/src/test/java/group/rxcloud/capa/configuration/CapaConfigurationClientBuilderTest.java
sdk/src/test/java/group/rxcloud/capa/configuration/CapaConfigurationClientStoreTest.java
sdk/src/test/java/group/rxcloud/capa/configuration/TestCapaConfigStore.java

1.add ut about configuration in sdk,component and spi module
2.fix bug in CapaConfigurationClientStore.
_Please explain the changes you've made_
Please reference the issue this PR will close: #11
* [ √] Code compiles correctly
* [ √] Created/updated tests

test:add ut about configuration in sdk,component and spi module

---

pom.xml

1. Remove arg.line properties
2. Extract maven.resource.version properties
see issue: https://github.com/reactivegroup/capa/issues/25
Please reference the issue this PR will close: #_[25]_

perf: Remove unused properties in pom.xml

---

examples/pom.xml
examples/src/main/java/group/rxcloud/capa/examples/rpc/DemoRpcClient.java
pom.xml
sdk-component/pom.xml
sdk-infrastructure/pom.xml
sdk-spi-demo/pom.xml
sdk-spi/pom.xml
sdk-spi/src/main/java/group/rxcloud/capa/spi/http/CapaHttpSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/http/CapaSerializeHttpSpi.java
sdk/pom.xml
sdk/src/main/java/group/rxcloud/capa/rpc/CapaRpcClientHttp.java

+ rpc add headers metric
+ add more log
https://github.com/reactivegroup/capa/issues/29

feat: add metric for rpc headers

---

examples/pom.xml
pom.xml
sdk-component/pom.xml
sdk-infrastructure/pom.xml
sdk-spi-demo/pom.xml
sdk-spi/pom.xml
sdk/pom.xml
sdk/src/main/java/group/rxcloud/capa/pubsub/CapaPubSubClient.java

try to set pom dependency in optional

chore: try to set pom dependency in optional

---

sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/log/agent/CapaLog4jAppenderAgentTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/log/agent/CapaLogbackAppenderAgentTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/log/agent/TestCapaLog4jAppender.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/log/agent/TestCapaLogbackAppender.java
sdk-component/src/test/resources/capa-component-log.properties

Add ut for logs
Add ut for logs.
#46 

test: Add ut for logs

---

pom.xml

_Please explain the changes you've made_

chore:add developer

---

sdk-component/src/main/java/group/rxcloud/capa/component/CapaConfigurationProperties.java
sdk-component/src/main/java/group/rxcloud/capa/component/configstore/CapaConfigStoreBuilder.java
sdk-component/src/main/java/group/rxcloud/capa/component/http/CapaHttp.java
sdk-component/src/main/resources/sample/capa-component-configuration-common.properties
sdk-infrastructure/pom.xml
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/CapaProperties.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/serializer/ObjectSerializer.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/utils/SpiUtils.java
sdk-infrastructure/src/main/resources/sample/capa-infrastructure-mixer.properties
sdk-spi-demo/src/main/java/group/rxcloud/capa/spi/demo/http/DemoCapaHttp.java
sdk-spi-demo/src/main/resources/capa-component-log.properties
sdk-spi/src/main/java/group/rxcloud/capa/spi/http/CapaHttpSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/http/CapaSerializeHttpSpi.java
sdk-spi/src/test/java/group/rxcloud/capa/spi/http/CapaSerializeHttpSpiTest.java

optimize capa code
https://github.com/reactivegroup/capa/issues/48

refactor: optimize code

---

sdk-component/src/main/java/group/rxcloud/capa/component/telemetry/metrics/CapaMeter.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/metrics/CapaDoubleHistogramBuilderTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/metrics/CapaMeterProviderTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/metrics/CapaMeterTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/metrics/CapaMetricsExporterTest.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/metrics/TestCapaMetricsExporter.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/metrics/TestLongHistogram.java
sdk-component/src/test/resources/capa-component-telemetry.properties
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaMeterSpi.java

Add comments and ut.
Add CapaMeterSpi.

Add comments and ut.

---

sdk-component/src/main/java/group/rxcloud/capa/component/telemetry/SamplerConfig.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/TestMixerProvider.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/hook/MergedPropertiesConfig.java

Add merged properties config.

---

examples/pom.xml
pom.xml
sdk-component/pom.xml
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/TestMixerProvider.java
sdk-infrastructure/pom.xml
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/hook/MergedPropertiesConfig.java
sdk-spi-demo/pom.xml
sdk-spi/pom.xml
sdk-springboot/pom.xml
sdk/pom.xml

Fix Configuration data type casting.

Fix Configuration data type casting.

---

sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/utils/SpiUtils.java

Change the log level while config file is not exists for telemetry.

---

examples/pom.xml
examples/src/main/resources/logback.xml
sdk-component/src/main/java/group/rxcloud/capa/component/log/CapaLogbackAppenderAgent.java
sdk-component/src/test/java/group/rxcloud/capa/component/log/TestCapaLogbackAppender.java
sdk-spi-demo/src/main/java/group/rxcloud/capa/spi/demo/log/DemoLogbackAppender.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/log/CapaLogbackAppenderSpi.java

add logback start

---

sdk-spi/src/main/java/group/rxcloud/capa/spi/log/manager/LogManager.java

update log switch

---

examples/pom.xml
pom.xml
sdk-component/pom.xml
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/TestMixerProvider.java
sdk-infrastructure/pom.xml
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/hook/Mixer.java
sdk-spi-demo/pom.xml
sdk-spi/pom.xml
sdk-springboot/pom.xml
sdk/pom.xml

_Please explain the changes you've made_

update pom version

---

examples/pom.xml
pom.xml
sdk-component/pom.xml
sdk-component/src/main/java/group/rxcloud/capa/component/telemetry/SamplerConfig.java
sdk-component/src/main/java/group/rxcloud/capa/component/telemetry/context/CapaContextPropagatorBuilder.java
sdk-component/src/main/java/group/rxcloud/capa/component/telemetry/context/ContextPropagatorLoader.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/context/CapaContextPropagatorBuilderTest.java
sdk-component/src/test/resources/capa-component-telemetry-sampling.properties
sdk-infrastructure/pom.xml
sdk-spi-demo/pom.xml
sdk-spi/pom.xml
sdk-springboot/pom.xml
sdk/pom.xml

1.Load all defined context propagators.
2.Change the user defined file name suffix to 'sampling'.

1.10.12.RELEASE

---

examples/pom.xml
pom.xml
sdk-component/pom.xml
sdk-component/src/main/java/group/rxcloud/capa/component/telemetry/context/CapaContextPropagatorBuilder.java
sdk-infrastructure/pom.xml
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/utils/SpiUtils.java
sdk-spi-demo/pom.xml
sdk-spi/pom.xml
sdk-spi/src/main/java/group/rxcloud/capa/spi/http/CapaHttpSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/http/CapaSerializeHttpSpi.java
sdk-spi/src/test/java/group/rxcloud/capa/spi/http/CapaSerializeHttpSpiTest.java
sdk-springboot/pom.xml
sdk/pom.xml
sdk/src/main/java/group/rxcloud/capa/rpc/Controller.java
sdk/src/main/java/group/rxcloud/capa/rpc/RequestMapping.java

feature: optimize rpc code

---

sdk-component/src/main/java/group/rxcloud/capa/component/CapaRpcProperties.java
sdk-component/src/main/java/group/rxcloud/capa/component/http/CapaHttp.java
sdk-component/src/main/java/group/rxcloud/capa/component/http/CapaHttpBuilder.java
sdk-component/src/test/java/group/rxcloud/capa/component/CapaRpcPropertiesTest.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/CapaClassLoader.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/CapaConstants.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/CapaProperties.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/plugin/PluginLoader.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/plugin/PluginOrder.java
sdk-infrastructure/src/test/java/group/rxcloud/capa/infrastructure/plugin/Plugin.java
sdk-infrastructure/src/test/java/group/rxcloud/capa/infrastructure/plugin/PluginImpl.java
sdk-infrastructure/src/test/java/group/rxcloud/capa/infrastructure/plugin/PluginLoaderTest.java
sdk-infrastructure/src/test/resources/META-INF/services/group.rxcloud.capa.infrastructure.plugin.Plugin
sdk-spi/src/main/java/group/rxcloud/capa/spi/configstore/CapaConfigStoreSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/http/config/CapaSpiProperties.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaContextAsyncWrapperSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaDoubleHistogramSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaLongHistogramSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaMeterSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaMetricsExporterSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaSpanBuilderSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaTracerBuilderSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/CapaTracerSpi.java
sdk-spi/src/main/java/group/rxcloud/capa/spi/telemetry/ContextPropagatorLoaderSpi.java
sdk/src/main/java/group/rxcloud/capa/rpc/CapaRpcClientBuilder.java

+ add plugin module.
+ optimize rpc code
+ add more comment

feat: add plugin module

---

sdk-component/src/main/java/group/rxcloud/capa/component/telemetry/SamplerConfig.java
sdk-component/src/test/java/group/rxcloud/capa/component/telemetry/SamplerConfigTest.java
sdk-infrastructure/src/main/java/group/rxcloud/capa/infrastructure/utils/SpiUtils.java
sdk-infrastructure/src/test/java/group/rxcloud/capa/infrastructure/utils/SpiUtilsTest.java

Remove the dependency of configuration during the initialization of telemetry client.

Remove the dependency of configuration during the initialization of telemetry client.

---

examples/pom.xml
pom.xml
sdk-component/pom.xml
sdk-infrastructure/pom.xml
sdk-spi-demo/pom.xml
sdk-spi/pom.xml
sdk-springboot/pom.xml
sdk/pom.xml

Upgrade version.
